POST http://localhost:8080/users/login
// --- this is authentication
Content-Type: application/json

{
    "email": "natankrasney@gmail.com", "password" : "123sae"
}


### 
GET http://localhost:8080/meetings
// --- this is authorization
// --- TODO CHANGE !!! put after Bearer the token you got from login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJuYXRhbmtyYXNuZXlAZ21haWwuY29tIiwiZXhwIjoxNTgwMTIwNDA3Ljg0MiwiaWF0IjoxNTgwMTE5MjA3fQ.-w3ihder2jn25qXu4kbpyOzMzxoasbwJcXiO8LgRzNI
